#! /bin/bash
echo "Configuring Environment...."
export ROOTSYS=/usr/lib/root-5.34.07/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/CommonUtils/lib
## now downloading required code from CVS
cd CommonUtils
CommonUtils=$(ls | grep TauDataFormat | wc -l)
cd ..
if [ $CommonUtils == 0 ]; then
    #Get PdtPdgMini
    cvs co -d CommonUtils/Validation/EventGenerator/interface -r HEAD CMSSW/Validation/EventGenerator/interface/PdtPdgMini.h
    cvs co -d CommonUtils/Validation/EventGenerator/src -r HEAD CMSSW/Validation/EventGenerator/src/PdtPdgMini.cc
    #Get TauDecay
    cvs co -d CommonUtils/Validation/EventGenerator/interface -r HEAD CMSSW/Validation/EventGenerator/interface/TauDecay.h
    cvs co -d CommonUtils/Validation/EventGenerator/src -r HEAD CMSSW/Validation/EventGenerator/src/TauDecay.cc
    
    #Get DataMCType
    cvs co -d CommonUtils/TauDataFormat/TauNtuple/interface -r HEAD UserCode/RWTH3b/Tau/FlatNtuple/TauDataFormat/TauNtuple/interface/DataMCType.h
    cvs co -d CommonUtils/TauDataFormat/TauNtuple/src -r HEAD UserCode/RWTH3b/Tau/FlatNtuple/TauDataFormat/TauNtuple/src/DataMCType.cc
fi


# now get TauSpiner
hepmc=$(ls TauSpiner/* | grep HepMC | wc -l) 
if [ $hepmc == 0 ]; then
    cd TauSpiner
    wget http://lcgapp.cern.ch/project/simu/HepMC/download/HepMC-2.06.05.tar.gz
    tar -xzvf HepMC-2.06.05.tar.gz
    mkdir hepmc
    cd hepmc/
    mkdir build install
    cd ../../
fi 
# use cvs version since CERN version is 3.6G and wget is corrupted --- hopefully can be fiex later
#wget http://www.hepforge.org/downloads/lhapdf/lhapdf-5.8.6.tar.gz
#wget http://www.hepforge.org/archive/lhapdf/pdfsets/current/MSTW2008nnlo90cl.LHgrid
lhapdf=$(ls TauSpiner/* | grep  lhapdf | wc -l)
if [ $lhapdf == 1 ]; then
    cd TauSpiner
    tar -xzvf lhapdf-5.8.6.tgz
    cd ..
fi
pythia=$(ls TauSpiner/* | grep pythia8135 | wc -l )
if [ $pythia == 0 ]; then 
    cd TauSpiner
    wget http://home.thep.lu.se/~torbjorn/pythia8/pythia8135.tgz
    tar -xzvf pythia8135.tgz
    cd ..
fi
tauola=$(ls TauSpiner/* | grep TAUOLA | wc -l )
if [ $tauola == 0 ]; then 
    cd TauSpiner
     wget http://annapurna.ifj.edu.pl/~tprzedzinski/resources/TAUOLA.1.1.1a/TAUOLA.1.1.1a.tar.gz
    tar -xzvf TAUOLA.1.1.1a.tar.gz
    cd ..
fi


export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/TauSpiner/TAUOLA/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/TauSpiner/pythia8135/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/TauSpiner/lhapdf/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/TauSpiner/hepmc/install/lib/


echo "Environment Configured"