#! /bin/bash
echo "Configuring Environment...."
export ROOTSYS=/usr/lib/root-5.34.00/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/CommonUtils/lib
## now downloading required code from CVS
cd CommonUtils
CommonUtils=$(ls | grep TauDataFormat | wc -l)
cd ..
if [ $CommonUtils == 0 ]; then
    #Get PdtPdgMini
    cvs co -d CommonUtils/TauDataFormat/TauNtuple/interface -r HEAD UserCode/RWTH3b/Tau/FlatNtuple/TauDataFormat/TauNtuple/interface/PdtPdgMini.h
    cvs co -d CommonUtils/TauDataFormat/TauNtuple/src -r HEAD UserCode/RWTH3b/Tau/FlatNtuple/TauDataFormat/TauNtuple/src/PdtPdgMini.cc
    #Get TauDecay
    cvs co -d CommonUtils/TauDataFormat/TauNtuple/interface -r HEAD UserCode/RWTH3b/Tau/FlatNtuple/TauDataFormat/TauNtuple/interface/TauDecay.h
    cvs co -d CommonUtils/TauDataFormat/TauNtuple/src -r HEAD UserCode/RWTH3b/Tau/FlatNtuple/TauDataFormat/TauNtuple/src/TauDecay.cc
    #Get DataMCType
    cvs co -d CommonUtils/TauDataFormat/TauNtuple/interface -r HEAD UserCode/RWTH3b/Tau/FlatNtuple/TauDataFormat/TauNtuple/interface/DataMCType.h
    cvs co -d CommonUtils/TauDataFormat/TauNtuple/src -r HEAD UserCode/RWTH3b/Tau/FlatNtuple/TauDataFormat/TauNtuple/src/DataMCType.cc
fi


# now get TauSpiner
hepmc=$(ls TauSpiner/* | grep HepMC | wc -l) 
if [ $hepmc == 0 ]; then
    cd TauSpiner
    wget http://lcgapp.cern.ch/project/simu/HepMC/download/HepMC-2.06.05.tar.gz
    tar -xzvf HepMC-2.06.05.tar.gz
    mkdir hepmc
    cd hepmc/
    mkdir build install
    cd ../../
fi 
# use cvs version since CERN version is 3.6G and wget is corrupted --- hopefully can be fiex later
#wget http://www.hepforge.org/downloads/lhapdf/lhapdf-5.8.6.tar.gz
#wget http://www.hepforge.org/archive/lhapdf/pdfsets/current/MSTW2008nnlo90cl.LHgrid
lhapdf=$(ls TauSpiner/* | grep  lhapdf | wc -l)
if [ $lhapdf == 1 ]; then
    cd TauSpiner
    tar -xzvf lhapdf-5.8.6.tgz
    cd ..
fi
pythia=$(ls TauSpiner/* | grep pythia8135 | wc -l )
if [ $pythia == 0 ]; then 
    cd TauSpiner
    wget http://home.thep.lu.se/~torbjorn/pythia8/pythia8135.tgz
    tar -xzvf pythia8135.tgz
    cd ..
fi
tauola=$(ls TauSpiner/* | grep tauola | wc -l )
if [ $tauola == 0 ]; then 
    cd TauSpiner
    cp /afs/cern.ch/sw/lcg/external/MCGenerators/distribution/tauola++-1.0.5-src.tgz .
    tar -xzvf tauola++-1.0.5-src.tgz
    cd ..
fi
tauspiner=$(ls TauSpiner/* | grep TauSpiner.v1.0 | wc -l )
if [ $tauspiner == 0  ]; then
    cd TauSpiner
    wget http://hibiscus.if.uj.edu.pl/~przedzinski/tau-reweight/downloads/release/TauSpiner.v1.0.tgz
    tar -xzvf TauSpiner.v1.0.tgz
    cp Makefile.TauSpiner TauSpiner.v1.0/Makefile
    mkdir TauSpiner.v1.0/lib
    mkdir TauSpiner.v1.0/include
    cd ..
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/TauSpiner/TauSpiner.v1.0/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/TauSpiner/tauola++/1.0.5/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/TauSpiner/pythia8135/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/TauSpiner/lhapdf/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/TauSpiner/hepmc/install/lib/


echo "Environment Configured"